### ISSUE TITLE
Switch from `@Transformer` to `@ServiceActivator`

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud-stream-app-starters/python#17]
As a developer, I'd like to switch from `@Transformer` to @ServiceActivator` to resolve an issue pertaining to SCSt 2.0 and content-type expectations.

child of https://github.com/spring-cloud-stream-app-starters/app-starters-release/issues/142.

**Comment by tzolov** [comment]
The `HttpJythonProcessorOutputConfiguration` processor already copies all inbound headers - including the `contentType`: https://goo.gl/DAvcAo . Therefore the copy-all-headers behavior is intentionally implemented by the processor and not introduced due to the `@Transformer` incorrect implementation (https://jira.spring.io/browse/INT-4397 ). 
Unless the processor implementation itself is incorrect (@dturanski ?) we can close this issue as `nothing to fix`.
